version: '2'

services:

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro

  nginx-gen:
    hostname: nginx-gen
    container_name: nginx-gen
    image: jwilder/docker-gen
    volumes_from:
      - nginx
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

  db:
    hostname: cafe-db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cafedb
      POSTGRES_PASSWORD: cafedbP4ss

  cafe-app:
    hostname: cafe-web
    image: yousan/nginx-unit
    container_name: nginx-unit
    ports:
      - 8200
    volumes:
      - ./json:/root/json
      - ./run:/var/run
      - ./root:/www/root
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=cafe.nokiosdesigns.com
      - LETSENCRYPT_HOST=cafe.nokiosdesigns.com
      - LETSENCRYPT_EMAIL=trenton.craig@gmail.com